#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Older-base-image fixture.
#
# Absorbs reuse category #7 from the migration spec: three hand-rolled
# Docker-older-base-image patterns in `test-rebuild-openclaw.sh`,
# `test-rebuild-hermes.sh`, and `test-sandbox-rebuild.sh`.
#
# Contract:
#   older_base_image_prepare <tag> [--registry ghcr.io/nvidia/nemoclaw]
#     Writes a minimal Dockerfile to a temp location whose first line is
#     `FROM <registry>:<tag>`, and prints the Dockerfile path on stdout.
#     Honors E2E_DRY_RUN: skips the `docker pull` step (but still writes
#     the Dockerfile, which is what callers inspect).
#   older_base_image_cleanup <dockerfile-path>
#     Removes the generated Dockerfile and (if present) its build context.

_E2E_OBI_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../runtime/lib" && pwd)"
# shellcheck source=../../runtime/lib/env.sh
. "${_E2E_OBI_LIB_DIR}/env.sh"

older_base_image_prepare() {
  local tag="${1:?tag required}"
  shift || true
  local registry="ghcr.io/nvidia/nemoclaw"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --registry)
        registry="${2:?value required}"
        shift 2
        ;;
      *)
        echo "older_base_image_prepare: unknown arg: $1" >&2
        return 2
        ;;
    esac
  done

  local dir
  dir="$(mktemp -d)"
  local dockerfile="${dir}/Dockerfile.older-base"
  cat >"${dockerfile}" <<EOF
FROM ${registry}:${tag}
# E2E older-base-image override \u2014 generated by older_base_image_prepare.
# This image is used only to exercise the rebuild/upgrade path and is
# torn down by older_base_image_cleanup.
LABEL nemoclaw.e2e.fixture=older-base-image
EOF

  e2e_env_trace "fixture:older-base-image" "${registry}:${tag}"
  if ! e2e_env_is_dry_run; then
    if command -v docker >/dev/null 2>&1; then
      docker pull "${registry}:${tag}" >&2 \
        || echo "older_base_image_prepare: docker pull failed (continuing; build may still succeed on cached layers)" >&2
    fi
  fi
  printf '%s\n' "${dockerfile}"
}

older_base_image_cleanup() {
  local dockerfile="${1:-}"
  if [[ -z "${dockerfile}" || ! -f "${dockerfile}" ]]; then
    return 0
  fi
  local dir
  dir="$(dirname "${dockerfile}")"
  rm -f "${dockerfile}"
  # Only remove the temp dir if it looks like one we created.
  case "${dir}" in
    /tmp/* | /var/folders/*) rm -rf "${dir}" ;;
  esac
}
