// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export type MigrationStatus = "targeted" | "remove-with-rationale";

export interface MigrationInventoryEntry {
  id: string;
  newOwner: string;
  status: MigrationStatus;
  rationale?: string;
}

const targeted = (id: string, newOwner: string): MigrationInventoryEntry => ({
  id,
  newOwner,
  status: "targeted",
});

export const migrationInventory = {
  setupScenarios: [
    targeted("ubuntu-repo-cloud-openclaw", "scenario:ubuntu-repo-cloud-openclaw"),
    targeted("ubuntu-repo-cloud-hermes", "scenario:ubuntu-repo-cloud-hermes"),
    targeted("gpu-repo-local-ollama-openclaw", "scenario:gpu-repo-local-ollama-openclaw"),
    targeted("macos-repo-cloud-openclaw", "scenario:macos-repo-cloud-openclaw"),
    targeted("wsl-repo-cloud-openclaw", "scenario:wsl-repo-cloud-openclaw"),
    targeted("brev-launchable-cloud-openclaw", "scenario:brev-launchable-cloud-openclaw"),
    targeted("ubuntu-no-docker-preflight-negative", "scenario:ubuntu-no-docker-preflight-negative"),
  ],
  baseScenarios: [
    targeted("ubuntu-repo-docker", "scenario environment helper:ubuntuRepoDocker"),
    targeted("gpu-repo-docker-cdi", "scenario environment helper:gpuRepoDockerCdi"),
    targeted("macos-repo-docker", "scenario environment helper:macosRepoDocker"),
    targeted("wsl-repo-docker", "scenario environment helper:wslRepoDocker"),
    targeted("brev-launchable-remote", "scenario environment helper:brevLaunchableRemote"),
    targeted("ubuntu-repo-no-docker", "scenario environment helper:ubuntuRepoNoDocker"),
  ],
  onboardingProfiles: [
    targeted("cloud-nvidia-openclaw", "manifest:openclaw-nvidia"),
    targeted("cloud-nvidia-hermes", "manifest:hermes-nvidia"),
    targeted("local-ollama-openclaw", "manifest:openclaw-ollama-gpu"),
    targeted("openai-compatible-openclaw", "manifest:openclaw-openai-compatible"),
    targeted("cloud-nvidia-openclaw-brave", "manifest:openclaw-nvidia-brave"),
    targeted("cloud-nvidia-openclaw-telegram", "manifest:openclaw-nvidia-telegram"),
    targeted("cloud-nvidia-openclaw-discord", "manifest:openclaw-nvidia-discord"),
    targeted("cloud-nvidia-openclaw-slack", "manifest:openclaw-nvidia-slack"),
    targeted("cloud-nvidia-hermes-discord", "manifest:hermes-nvidia-discord"),
    targeted("cloud-nvidia-hermes-slack", "manifest:hermes-nvidia-slack"),
    targeted("cloud-nvidia-openclaw-resume-after-interrupt", "manifest:openclaw-nvidia-resume"),
    targeted("cloud-nvidia-openclaw-repair-existing-config", "manifest:openclaw-nvidia-repair"),
    targeted("cloud-nvidia-openclaw-double-same-provider", "manifest:openclaw-nvidia-double-same-provider"),
    targeted("cloud-nvidia-openclaw-double-provider-switch", "manifest:openclaw-nvidia-double-provider-switch"),
    targeted("cloud-nvidia-openclaw-token-rotation", "manifest:openclaw-nvidia-token-rotation"),
  ],
  testPlans: [
    targeted("ubuntu-repo-docker__cloud-nvidia-openclaw", "scenario:ubuntu-repo-cloud-openclaw"),
    targeted("ubuntu-repo-docker__cloud-nvidia-hermes", "scenario:ubuntu-repo-cloud-hermes"),
    targeted("gpu-repo-docker-cdi__local-ollama-openclaw", "scenario:gpu-repo-local-ollama-openclaw"),
    targeted("macos-repo-docker__cloud-nvidia-openclaw", "scenario:macos-repo-cloud-openclaw"),
    targeted("wsl-repo-docker__cloud-nvidia-openclaw", "scenario:wsl-repo-cloud-openclaw"),
    targeted("brev-launchable-remote__cloud-nvidia-openclaw", "scenario:brev-launchable-cloud-openclaw"),
    targeted("ubuntu-repo-no-docker__cloud-nvidia-openclaw", "scenario:ubuntu-no-docker-preflight-negative"),
    targeted("ubuntu-repo-docker__openai-compatible-openclaw", "scenario:ubuntu-repo-openai-compatible-openclaw"),
    targeted("ubuntu-repo-docker__cloud-nvidia-openclaw-brave", "scenario:ubuntu-repo-cloud-openclaw-brave"),
    targeted("ubuntu-repo-docker__cloud-nvidia-openclaw-telegram", "scenario:ubuntu-repo-cloud-openclaw-telegram"),
    targeted("ubuntu-repo-docker__cloud-nvidia-openclaw-discord", "scenario:ubuntu-repo-cloud-openclaw-discord"),
    targeted("ubuntu-repo-docker__cloud-nvidia-openclaw-slack", "scenario:ubuntu-repo-cloud-openclaw-slack"),
    targeted("ubuntu-repo-docker__cloud-nvidia-hermes-discord", "scenario:ubuntu-repo-cloud-hermes-discord"),
    targeted("ubuntu-repo-docker__cloud-nvidia-hermes-slack", "scenario:ubuntu-repo-cloud-hermes-slack"),
    targeted("ubuntu-repo-docker__cloud-nvidia-openclaw-resume-after-interrupt", "scenario:ubuntu-repo-cloud-openclaw-resume"),
    targeted("ubuntu-repo-docker__cloud-nvidia-openclaw-repair-existing-config", "scenario:ubuntu-repo-cloud-openclaw-repair"),
    targeted("ubuntu-repo-docker__cloud-nvidia-openclaw-double-same-provider", "scenario:ubuntu-repo-cloud-openclaw-double-same-provider"),
    targeted("ubuntu-repo-docker__cloud-nvidia-openclaw-double-provider-switch", "scenario:ubuntu-repo-cloud-openclaw-double-provider-switch"),
    targeted("ubuntu-repo-docker__cloud-nvidia-openclaw-token-rotation", "scenario:ubuntu-repo-cloud-openclaw-token-rotation"),
  ],
  expectedStates: [
    targeted("cloud-openclaw-ready", "assertion modules:cloudOpenClawReady"),
    targeted("macos-cli-ready-docker-optional", "assertion modules:macosCliDockerOptional"),
    targeted("cloud-hermes-ready", "assertion modules:cloudHermesReady"),
    targeted("local-ollama-openclaw-ready", "assertion modules:localOllamaOpenClawReady"),
    targeted("preflight-failure-no-sandbox", "assertion modules:preflightFailureNoSandbox"),
    targeted("cloud-openclaw-custom-policies-ready", "assertion modules:cloudOpenClawCustomPoliciesReady"),
    targeted("onboarding-failure-invalid-nvidia-key", "assertion modules:onboardingFailureInvalidNvidiaKey"),
    targeted("onboarding-failure-gateway-port-conflict", "assertion modules:onboardingFailureGatewayPortConflict"),
  ],
  onboardingAssertions: [
    targeted("base-installed", "assertion:onboarding.base.cli-installed"),
    targeted("preflight-passed", "assertion:onboarding.preflight.passed"),
    targeted("preflight-expected-failed", "assertion:onboarding.preflight.expected-failed"),
  ],
  validationSuites: [
    targeted("smoke", "assertion:runtime.smoke"),
    targeted("inference", "assertion:runtime.inference"),
    targeted("credentials", "assertion:runtime.credentials"),
    targeted("local-ollama-inference", "assertion:runtime.local-ollama-inference"),
    targeted("ollama-proxy", "assertion:runtime.ollama-proxy"),
    targeted("platform-macos", "assertion:platform.macos"),
    targeted("platform-wsl", "assertion:platform.wsl"),
    targeted("hermes-specific", "assertion:runtime.hermes-specific"),
    targeted("gateway-health", "assertion:runtime.gateway-health"),
    targeted("sandbox-shell", "assertion:runtime.sandbox-shell"),
    targeted("cloud-inference", "assertion:runtime.cloud-inference"),
    targeted("ollama-auth-proxy", "assertion:runtime.ollama-auth-proxy"),
    targeted("security-credentials", "assertion:security.credentials"),
    targeted("messaging-telegram", "assertion:messaging.telegram"),
    targeted("messaging-discord", "assertion:messaging.discord"),
    targeted("messaging-slack", "assertion:messaging.slack"),
    targeted("security-shields", "assertion:security.shields"),
    targeted("inference-routing", "assertion:runtime.inference-routing"),
    targeted("sandbox-lifecycle", "assertion:lifecycle.sandbox-lifecycle"),
    targeted("sandbox-operations", "assertion:lifecycle.sandbox-operations"),
    targeted("snapshot", "assertion:lifecycle.snapshot"),
    targeted("rebuild", "assertion:lifecycle.rebuild"),
    targeted("upgrade", "assertion:lifecycle.upgrade"),
    targeted("diagnostics", "assertion:diagnostics"),
    targeted("docs-validation", "assertion:docs-validation"),
    targeted("openai-compatible-inference", "assertion:runtime.openai-compatible-inference"),
    targeted("inference-switch", "assertion:runtime.inference-switch"),
    targeted("kimi-compatibility", "assertion:runtime.kimi-compatibility"),
    targeted("messaging-token-rotation", "assertion:messaging.token-rotation"),
    targeted("security-policy", "assertion:security.policy"),
    targeted("security-injection", "assertion:security.injection"),
    targeted("baseline-onboarding", "assertion:baseline.onboarding"),
    targeted("model-router", "assertion:runtime.model-router"),
    targeted("onboarding-state", "assertion:onboarding.state"),
    targeted("snapshot-lifecycle", "assertion:lifecycle.snapshot"),
  ],
  validationSuiteScripts: [
    targeted("baseline-onboarding/00-cli-and-openshell.sh", "assertion step:baseline.cli-and-openshell"),
    targeted("baseline-onboarding/01-sandbox-state.sh", "assertion step:baseline.sandbox-state"),
    targeted("baseline-onboarding/02-route-and-smoke.sh", "assertion step:baseline.route-and-smoke"),
    targeted("hermes/00-hermes-health.sh", "assertion step:runtime.hermes.health"),
    targeted("inference/cloud/00-models-health.sh", "assertion step:runtime.inference.models-health"),
    targeted("inference/cloud/01-chat-completion.sh", "assertion step:runtime.inference.chat-completion"),
    targeted("inference/cloud/02-inference-local-from-sandbox.sh", "assertion step:runtime.inference.sandbox-local"),
    targeted("inference/kimi-compatibility/00-plugin-wiring.sh", "assertion step:runtime.kimi.plugin-wiring"),
    targeted("inference/kimi-compatibility/01-kimi-compatible-models-route.sh", "assertion step:runtime.kimi.compatible-models-route"),
    targeted("inference/model-router/00-healthy-endpoint.sh", "assertion step:runtime.model-router.healthy-endpoint"),
    targeted("inference/model-router/01-provider-routed-completion.sh", "assertion step:runtime.model-router.provider-routed-completion"),
    targeted("inference/ollama-auth-proxy/00-proxy-reachable.sh", "assertion step:runtime.ollama-auth-proxy.reachable"),
    targeted("inference/ollama-auth-proxy/01-auth-enforcement.sh", "assertion step:runtime.ollama-auth-proxy.auth-enforcement"),
    targeted("inference/ollama-gpu/00-ollama-models-health.sh", "assertion step:runtime.ollama.models-health"),
    targeted("inference/routing/00-inference-local-chat-completion.sh", "assertion step:runtime.inference.routing-chat"),
    targeted("inference/routing/01-provider-route-health.sh", "assertion step:runtime.inference.provider-route-health"),
    targeted("inference/switch/00-route-state-updated.sh", "assertion step:runtime.inference.route-state-updated"),
    targeted("inference/switch/01-switched-inference-local-chat.sh", "assertion step:runtime.inference.switched-local-chat"),
    targeted("inference/ollama-gpu/01-ollama-chat-completion.sh", "assertion step:runtime.ollama.chat-completion"),
    targeted("platform/macos/00-macos-smoke.sh", "assertion step:platform.macos.smoke"),
    targeted("platform/wsl/00-wsl-smoke.sh", "assertion step:platform.wsl.smoke"),
    targeted("onboarding/state/00-registry-provider-model-policies.sh", "assertion step:onboarding.state.registry"),
    targeted("onboarding/state/01-session-provider-model-policies.sh", "assertion step:onboarding.state.session"),
    targeted("rebuild_upgrade/00-state-preserved.sh", "assertion step:lifecycle.rebuild.state-preserved"),
    targeted("rebuild_upgrade/01-agent-version-upgraded.sh", "assertion step:lifecycle.rebuild.agent-version-upgraded"),
    targeted("rebuild_upgrade/02-post-rebuild-inference.sh", "assertion step:lifecycle.rebuild.post-rebuild-inference"),
    targeted("rebuild_upgrade/03-policy-config-preserved.sh", "assertion step:lifecycle.upgrade.policy-config-preserved"),
    targeted("rebuild_upgrade/04-upgrade-survivor-reachable.sh", "assertion step:lifecycle.upgrade.survivor-reachable"),
    targeted("sandbox/lifecycle/00-gateway-health.sh", "assertion step:lifecycle.sandbox.gateway-health"),
    targeted("sandbox/lifecycle/01-gateway-recovery.sh", "assertion step:lifecycle.sandbox.gateway-recovery"),
    targeted("sandbox/operations/00-list-and-status.sh", "assertion step:lifecycle.sandbox.list-and-status"),
    targeted("sandbox/operations/01-logs-and-exec.sh", "assertion step:lifecycle.sandbox.logs-and-exec"),
    targeted("sandbox/snapshot/00-create-list-restore.sh", "assertion step:lifecycle.snapshot.create-list-restore"),
    targeted("security/credentials/00-credentials-present.sh", "assertion step:security.credentials.present"),
    targeted("security/credentials/01-no-plaintext-host-store.sh", "assertion step:security.credentials.no-plaintext-host-store"),
    targeted("security/injection/00-telegram-message-not-shell-executed.sh", "assertion step:security.injection.blocked"),
    targeted("security/policy/00-telegram-preset-applied.sh", "assertion step:security.policy.telegram-preset"),
    targeted("security/policy/01-openshell-version-supports-credential-rewrite.sh", "assertion step:security.policy.credential-rewrite"),
    targeted("security/shields/00-config-consistent.sh", "assertion step:security.shields.config"),
    targeted("smoke/00-cli-available.sh", "assertion step:runtime.smoke.cli-available"),
    targeted("smoke/01-gateway-health.sh", "assertion step:runtime.smoke.gateway-health"),
    targeted("smoke/02-sandbox-listed.sh", "assertion step:runtime.smoke.sandbox-listed"),
    targeted("smoke/03-sandbox-shell.sh", "assertion step:runtime.smoke.sandbox-shell"),
    targeted("messaging/common/00-provider-attached.sh", "assertion step:messaging.common.provider-attached"),
    targeted("messaging/common/01-placeholder-configured.sh", "assertion step:messaging.common.placeholder-configured"),
    targeted("messaging/common/02-no-secret-leak.sh", "assertion step:messaging.common.no-secret-leak"),
    targeted("messaging/common/03-bridge-reachable.sh", "assertion step:messaging.common.bridge-reachable"),
    targeted("messaging/discord/00-discord-gateway-path.sh", "assertion step:messaging.discord.gateway-path"),
    targeted("messaging/slack/00-slack-provider-state.sh", "assertion step:messaging.slack.provider-state"),
    targeted("messaging/telegram/00-telegram-injection-safety.sh", "assertion step:messaging.telegram.injection-safety"),
    targeted("messaging/telegram/01-telegram-injection-payload-classes.sh", "assertion step:messaging.telegram.injection-payload-classes"),
    targeted("messaging/token-rotation/00-provider-rotation-isolated.sh", "assertion step:messaging.token-rotation"),
  ],
} as const;
